apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-teemii.yaml
  - gitrepository-teemii.yaml
  - helmchart-teemii.yaml

namespace: teemii-flux

commonLabels:
  managed-by: flux
  project: teemii
