apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository-teemi.yaml
  - helmrelease-teemi.yaml

namespace: teemii-flux

commonLabels:
  managed-by: flux
  project: teemii
